#!/usr/bin/ruby
# Extract integrator files from archive
require 'yaml'
require 'catalog/astdys.rb'
require 'mercury/mercury6.rb'
require 'classes/colorize.rb'
require 'commands/command.rb'
require 'classes/functions.rb'
require 'classes/asteroid.rb'
require 'classes/resonance_archive.rb'
require 'classes/resonance_database.rb'
require 'classes/series.rb'
require 'classes/view.rb'
require 'axis/finder.rb'

num_b = CONFIG['integrator']['number_of_bodies']

start    = get_command_line_argument('start', false)
stop     = get_command_line_argument('stop',  false)

action = false
action = ARGV[0] if !ARGV.empty?

if (!action)
  print "[Warning]".to_red+' Please, specify action: '
  action = gets.to_s
end

if (!start)
  print "[Warning]".to_red+' Please, specify first object number: '
  start  = gets
end

start = start.to_i

if (!stop)
  stop = start + CONFIG['integrator']['number_of_bodies']
end
stop = stop.to_i

action.strip!

case action

when 'show'
  puts 'show'
  
when 'plot'
  Command.plot(start, stop)
  puts 'plot'

when 'package'
  clean = get_command_line_argument('clean', false)
  res   = get_command_line_argument('res', false)
  aei   = get_command_line_argument('aei', false)
  zip   = get_command_line_argument('zip', false)
  Command.package(start, clean, res, aei, zip)

when 'extract'
  copy_aei = get_command_line_argument('copy_aei', false)
  Command.extract(start, copy_aei)

when 'extract-mass'
  copy_aei = get_command_line_argument('copy_aei', false)
  Command.extract_mass(start, stop, copy_aei)
  
when 'rcopy'
  Command.rcopy(start, stop)
  
when 'stat'
  gcd = get_command_line_argument('gcd', false)
  export = get_command_line_argument('export', false)
  Command.stat(gcd, export)

when 'stat-table'
  Command.stat_table

when 'stat-order'
  pure = get_command_line_argument('pure', false)
  sum_module = get_command_line_argument('sum_module', false)
  Command.stat_order(pure, sum_module)
 
when 'find'
  current = get_command_line_argument('current', false)
  Command.find(start, current)

when 'find-mass'
  Command.find_mass(start, stop)
  
when 'calc'
  Command.calc(start)

when 'calc-mass'
  Command.calc_mass(start, stop)

when 'resonance-show'
  resonance = get_command_line_argument('resonance', false)
  resonance = resonance.delete('[').delete(']').split(',').map{|x| x.to_f}
  Command.resonance_show(resonance)

when 'mediana'
  Command.mediana(start)

when 'mediana-mass'
  resonance = get_command_line_argument('resonance', false)
  Command.mediana_mass(start, stop, resonance)

when 'resonances'
  resonance = get_command_line_argument('resonance', false)
  resonance = resonance.delete('[').delete(']').split(',').map{|x| x.to_f} if resonance
  Command.resonances(start, stop, resonance)

when 'results'
  resonance = get_command_line_argument('resonance', false)
  file      = get_command_line_argument('file', false)
  pure      = get_command_line_argument('pure', false)
  three_body = get_command_line_argument('three_body', false)
  three_body = false if three_body == "0"
  s = pure.split(',').map{|elem| elem.to_i}
  Command.results(file, resonance, s, three_body)

when 'complex'

else
  puts 'Specify command'

end
