debug: false

resonances:
  format: simple
  file: axis/resonances
  axis_error: 0.01
  libration:
    min: 20000
  db: export/full.db
  bodies:
    - JUPITER
    - SATURN
  bodies_numbers:
    - 5
    - 6
  
catalog:
  astdys: 
    file:  catalog/allnum.cat
    skip:  6
    class: AstDySCatalog
  proper: 
    file:  catalog/allnum.pro
    skip:  3
    class: ProperCatalog
  mean:   
    file:  catalog/allnum.mea
    skip:  3
    class: MeanCatalog
  synthetic: 
    file:  catalog/numb.syn
    skip:  2
    class: SyntethicCatalog

integrator:
  type: mercury6
  input: input/mercury
  
  dir: mercury
  
  files:
    small_bodies: small.in

  start: 2455400.5
  step:  3650.25
  number_of_bodies: 100

output:
  angle:   output/res
  gnuplot: output/gnu
  images:  output/images

  format:  png

export:
  format: simple
  
  variables:
    Fixnum: %6d
    Float:  %10.4f
    String: %s
  
  base_dir: export
  aei_dir:  aei
  structure:
    - aei
    - mercury
    - res
    - png
    - resonances
    - gnu

gnuplot:
  x_stop: 100000
  type:   points
  
server:
  username:   root
  address:    uranus
  source_dir: /root/resonances
  dest_dir:   /Users/smirik/projects/resonances

constants:
  u:  0.0002959122082855911025
  k:  0.017202098795
  k2: 0.0002959122082855911025

  planets:
    - 0.0
    - 1.66014780554019e-07
    - 2.44733799205671e-06
    - 3.00316726157559e-06
    - 3.22683625760394e-07
    - 0.000954502036096727
    - 0.000285787542104469
    - 4.36378261525313e-05
    - 5.14956512995827e-05
    - 6.56075612085868e-09

  axis:
    - 0.0
    - 0.0
    - 0.723332
    - 1.00000261
    - 1.523679
    - 5.204267
    - 9.58201720
# in sec
  mean_motion:
    - 0.0
    - 0.0
    - 2106626.16642123
    - 1297281.96342998
    - 689017.369124865
    - 109256.679
    - 43995.910    
  longitude_of_periapsis:
    - 0.0
    - 0.0
    - 7.452
    - 17.368
    - 17.916
    - 4.257
    - 28.243
